services:
  backend:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./backend
      dockerfile: ../deploy/backend.Dockerfile
    container_name: uni_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:54322/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../deploy/frontend.Dockerfile
    container_name: uni_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
