spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/canpan_board
    username: canpan_user
    password: canpan_pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # creates/updates schemas automatically
    show-sql: true       # shows sql commands in terminal
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
